### ISSUE TITLE
Need help to setup firebase database

### ISSUE THREAD

**Issue by bhavin1994** [Fruit-Punch-Samurai/FireChat#1]
Hi,

I liked your coding. You did good work i installed your app its working very well I just want to know What data base you used in firebase. Is It Real time database or Cloud Firestore database ? If it's cloud firestore db then it is Native mode and Datastore mode?

Please help me to setup Firebase DATABASE which you used in this repo.

Thanks

**Comment by Yaya-Dev-Box** [comment]
Hi, glad you liked my little project. For the database I used "Cloud
Firestore" in native mode.
Happy coding :)
